# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-30 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Climate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=15)),
                ('season', models.CharField(max_length=4)),
                ('year', models.IntegerField(default=0)),
                ('tmin', models.IntegerField(default=0)),
                ('tmean', models.IntegerField(default=0)),
                ('tmax', models.IntegerField(default=0)),
                ('sunshine', models.IntegerField(default=0)),
                ('rainfall', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=15)),
                ('attribute', models.CharField(max_length=15)),
                ('season', models.CharField(max_length=4)),
                ('year', models.IntegerField(default=0)),
                ('value', models.IntegerField(default=0)),
            ],
        ),
    ]
