# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-05 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Climate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=15)),
                ('season', models.CharField(max_length=4)),
                ('year', models.IntegerField(default=0)),
                ('tmin', models.FloatField(default=0)),
                ('tmean', models.FloatField(default=0)),
                ('tmax', models.FloatField(default=0)),
                ('sunshine', models.FloatField(default=0)),
                ('rainfall', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=15)),
                ('attribute', models.CharField(max_length=15)),
                ('season', models.CharField(max_length=4)),
                ('year', models.IntegerField(default=9999)),
                ('value', models.FloatField(default=999999)),
            ],
        ),
        migrations.AddIndex(
            model_name='weather',
            index=models.Index(fields=['region', 'year', 'season', 'attribute'], name='metoffice_w_region_d5b9e7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='weather',
            unique_together=set([('region', 'year', 'season', 'attribute')]),
        ),
        migrations.AddIndex(
            model_name='climate',
            index=models.Index(fields=['region', 'year', 'season'], name='metoffice_c_region_a1dab6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='climate',
            unique_together=set([('region', 'year', 'season')]),
        ),
    ]
