# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-05 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metoffice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='value',
            field=models.FloatField(default=9999),
        ),
    ]
